services:
  api:
    build:
      context: .
      dockerfile: ./API/Dockerfile
    image: georgi-api
    ports:
      - "80:80"
  client:
    build:
      context: .
      dockerfile: ./Client/Dockerfile
    image: georgi-react
    ports:
      - "3000:3000"
  db:
    image: "postgis/postgis"
    build:
      context: .
      dockerfile: pg-Dockerfile
    volumes:
      - ./Postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=Pass2020!
      - POSTGRES_PASSWORD=Pass2020!
      - ALLOW_IP_RANGE=0.0.0.0/0
      - POSTGRES_MULTIPLE_EXTENSIONS=hstore,postgis,postgis_topology,postgis_raster,pgrouting
    ports:
      - "5432:5432"
    restart: on-failure
    healthcheck:
      test: "exit 0"

volumes:
  Postgres-data:
